
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'
  - name: cfn
    before: |
      pip install cfn-lint
      cargo install cfn-guard
      gem install cfn-toml
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      bash bin/ecr/login
    command: aws --version
  - name: flask
    command: |
      ruby $THEIA_WORKSPACE_ROOT/bin/backend/generate-env
      ruby $THEIA_WORKSPACE_ROOT/bin/backend/generate-env-local
      cd backend-flask
      pip install -r requirements.txt
  # - name: momento
  #   before: |
  #     brew tap momentohq/tap
  #     brew install momento-cli
  - name: react-js
    command: |
      ruby $THEIA_WORKSPACE_ROOT/bin/frontend/generate-env
      ruby $THEIA_WORKSPACE_ROOT/bin/frontend/generate-env-local
      cd frontend-react-js
      npm i
  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      gp env GITPOD_IP=$(curl ifconfig.me)
      source  "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"
  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      cd backend-flask
  - name: cdk
    before: |
      npm install aws-cdk -g
      cd thumbing-serverless-cdk
      npm i

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - ms-python.python  
    - eamodio.gitlens
    - mhutchie.git-graph
    - ms-azuretools.vscode-docker
