# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    runtime-versions:
      # docker: 20
      python: 3.10
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR/backend"
      - cd $CODEBUILD_SRC_DIR
      - echo "Installing Python 3.10"
      - pyenv install 3.10.0  # Install Python 3.10 using pyenv
      - pyenv global 3.10.0   # Set Python 3.10 as the default version
      - python --version      # Verify the installed Python version
      - ./bin/backend/generate-env
      - cd $CODEBUILD_SRC_DIR/backend-flask
      - AWS_ECR_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $AWS_ECR_PASSWORD | docker login --username AWS --password-stdin $IMAGE_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile.prod -t backend-flask .
      - "docker tag $REPO_NAME $IMAGE_URL/$REPO_NAME"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push $IMAGE_URL/$REPO_NAME
      - cd $CODEBUILD_SRC_DIR
      - echo "imagedefinitions.json > [{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json
      - printf "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json

env:
  variables:
    AWS_ACCOUNT_ID: 197942459570
    AWS_DEFAULT_REGION: ap-south-1
    CONTAINER_NAME: backend-flask
    IMAGE_URL: 197942459570.dkr.ecr.ap-south-1.amazonaws.com
    REPO_NAME: backend-flask:latest

artifacts:
  files:
    - imagedefinitions.json
