AWSTemplateFormatVersion: 2010-09-09
Description: |
  Codebuild used for baking container images
  - Codebuild Project
  - Codebuild Project Role
Parameters:
  LogGroupPath:
    Type: String
    Description: "The log group path for CodeBuild"
    Default: "/cruddur/codebuild/bake-service"
  LogStreamName:
    Type: String
    Description: "The log group path for CodeBuild"
    Default: "backend-flask"
  CodeBuildImage:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  CodeBuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
  CodeBuildTimeoutMins:
    Type: Number
    Default: 5
  QueueTimeoutMins:
    Type: Number
    Default: 480
  BuildSpec:
    Type: String
    Default: 'backend-flask/buildspec.yml'
  GithubRepoUrl:
    Type: String
    Default: 'https://github.com/aravindvcyber/aws-bootcamp-cruddur-2023.git'
  ArtifactBucketName:
    Type: String
  
Resources:
  CodeBuildProject:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cfn-cruddur-backend-flask-bake-image
      QueuedTimeoutInMinutes: !Ref QueueTimeoutMins
      ServiceRole: !GetAtt CodeBuildRole.Arn
      BadgeEnabled: true
      ConcurrentBuildLimit: 2
      # PrivilegedMode is needed to build Docker images
      # even though we have No Artifacts, CodePipeline Demands both to be set as CODEPIPLINE
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: !Ref CodeBuildComputeType
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: "ap-south-1" 
          - Name: ENVIRONMENT
            Value: "PROD" 
          - Name: AWS_REGION
            Value: "ap-south-1"
          - Name: AWS_CNAME
            Value: "cruddur.sandbox.exploringserverless.com"
          - Name: AWS_ACCESS_KEY_ID
            Type: PARAMETER_STORE
            Value: /cruddur/backend-flask/AWS_ACCESS_KEY_ID
          - Name: AWS_SECRET_ACCESS_KEY
            Type: PARAMETER_STORE
            Value: /cruddur/backend-flask/AWS_SECRET_ACCESS_KEY
          - Name: CONNECTION_URL
            Type: PARAMETER_STORE
            Value: /cruddur/backend-flask/CONNECTION_URL
          - Name: OTEL_EXPORTER_OTLP_HEADERS
            Type: PARAMETER_STORE
            Value: /cruddur/backend-flask/OTEL_EXPORTER_OTLP_HEADERS
          - Name: ROLLBAR_ACCESS_TOKEN
            Type: PARAMETER_STORE
            Value: /cruddur/backend-flask/ROLLBAR_ACCESS_TOKEN
      TimeoutInMinutes: !Ref CodeBuildTimeoutMins
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogGroupPath
          Status: ENABLED
          StreamName: !Ref LogStreamName
      Source:
        Type: GITHUB
        Location: !Ref GithubRepoUrl
        GitCloneDepth: 1
        SourceIdentifier: prod
        ReportBuildStatus: true
        BuildSpec: !Ref BuildSpec
      SourceVersion: prod
  CodeBuildRole:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /service-role/
      Policies:
        # - PolicyName: !Sub ${AWS::StackName}S3access
        #   PolicyDocument:
        #     Version: '2012-10-17'
        #     Statement:
        #       - Action:
        #         - s3:PutObject
        #         - s3:GetObject
        #         - s3:GetObjectVersion
        #         - s3:GetBucketAcl
        #         - s3:GetBucketLocation
        #         Effect: Allow
        #         Resource:
        #           - !Sub arn:aws:s3:::codepipeline-ap-south-1-*
        #           - !Sub arn:aws:s3:::codepipeline-cruddur-sandbox-artifacts*
        - PolicyName: !Sub ${AWS::StackName}ReportGroup
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - codebuild:CreateReportGroup
                - codebuild:CreateReport
                - codebuild:UpdateReport
                - codebuild:BatchPutTestCases
                - codebuild:BatchPutCodeCoverages
                Effect: Allow
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:codepipeline-ap-south-1-*
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:codepipeline-cruddur-sandbox-artifacts*
        - PolicyName: !Sub ${AWS::StackName}Logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/cruddur/codebuild/bake-service
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/cruddur/codebuild/bake-service:log-stream:backend-flask/*
        - PolicyName: !Sub ${AWS::StackName}S3ArtifactAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - s3:*
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucketName}
                  - !Sub arn:aws:s3:::${ArtifactBucketName}/*
        - PolicyName: !Sub ${AWS::StackName}SSMAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - ssm:GetParameters
                - ssm:GetParameter
                Effect: Allow
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cruddur/backend-flask/*
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CodeBuild/*
Outputs:
  CodeBuildProjectName:
    Description: "CodeBuildProjectName"
    Value: !Ref CodeBuildProject