[deploy]
bucket = 'cfn-sandbox-artifacts'
region = 'ap-south-1'
stack_name = 'CrdCicd'


[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'aravindvcyber/aws-bootcamp-cruddur-2023'
GithubRepoUrl = 'https://github.com/aravindvcyber/aws-bootcamp-cruddur-2023.git'
ArtifactBucketName = "codepipeline-cruddur-sandbox-artifacts"