# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths: ["frontend-react-js/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["frontend-react-js/**"]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        CI: false
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      name: checkout mono repo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend-react-js/package-lock.json'
    - name: npm cd and install
      working-directory: frontend-react-js
      run: |
        npm ci
    - name: npm build and test
      working-directory: frontend-react-js
      run: |
        npm run build --if-present
    - name: Notify deploy to Rollbar
      uses: rollbar/github-deploy-action@2.1.1
      id: rollbar_deploy
      with:
        environment: 'main'
        version: ${{ github.sha }}
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN_FRONTEND }}
        ROLLBAR_USERNAME: ${{ github.actor }}
