name: Sync-Prod-Frontend

on:
  push:
    branches: [ prod ]
  # pull_request:
  #   branches: [ prod ]

jobs:
  build:
    name: Statically Build Files
    runs-on: ubuntu-latest
    env:
        CI: false
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
        name: checkout mono repo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend-react-js/package-lock.json'
      - name: npm cd and install
        working-directory: frontend-react-js
        run: |
          npm ci
      - name: npm build and test
        working-directory: frontend-react-js
        run: |
          npm run build --if-present
  approval-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Log event payload
          run: echo '${{ toJson(github.event) }}'
        - name: Approve or Reject
          id: approval
          uses: "actions/github-script@v6"
          with:
            script: |
              const response = await github.actions.createApproval({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                run_id: context.payload.workflow_run.id,
                event: 'APPROVE'
              });
              console.log(response.data);
        - name: Check Approval Status
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const response = await github.actions.getWorkflowRun({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                run_id: context.payload.workflow_run.id
              });
              const conclusion = response.data.conclusion;
              console.log(`Approval Status: ${conclusion}`);
  deploy:
    name: Sync Static Build to S3 Bucket
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: approval-job
    env: 
        SYNC_S3_BUCKET: ${{ secrets.SYNC_S3_BUCKET }}
        SYNC_CLOUDFRONT_DISTRUBTION_ID: ${{ secrets.SYNC_CLOUDFRONT_DISTRUBTION_ID }}
        SYNC_BUILD_DIR: "frontend-react-js/build"
        SYNC_OUTPUT_CHANGESET_PATH: "tmp/changeset.json"
        SYNC_AUTO_APPROVE: false

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::197942459570:role/CrdSyncRole-Role-LY8UABQRSNZ8
          aws-region: ap-south-1
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake sync